version: '3'
services:
  db:
    image: "mongo"
    hostname: vet-faucet-db
    ports:
      - "27017:27017"
    volumes:
      - .tmp/data:/data
  web:
    build: .
    hostname: vet-faucet-web
    ports:
      - "8000:8000"
    volumes:
      - configs:/opt/vet-faucet/configs:ro
    depends_on:
      - db
    links:
      - db
volumes:
  configs:
    external: true
