version: '3'
services:
  db:
    image: "mongo"
    ports:
      - "27017:27017"
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - configs:/opt/vet-faucet/configs:ro
    depends_on:
      - db
    links:
      - db
volumes:
  configs:
    external: true
